// Code generated by "enumer -sql -type=DownloadState -output=enum_download_state.go"; DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _DownloadStateName = "DownloadUnknownDownloadQueuedDownloadDownloadingDownloadCompleteDownloadError"

var _DownloadStateIndex = [...]uint8{0, 15, 29, 48, 64, 77}

const _DownloadStateLowerName = "downloadunknowndownloadqueueddownloaddownloadingdownloadcompletedownloaderror"

func (i DownloadState) String() string {
	if i < 0 || i >= DownloadState(len(_DownloadStateIndex)-1) {
		return fmt.Sprintf("DownloadState(%d)", i)
	}
	return _DownloadStateName[_DownloadStateIndex[i]:_DownloadStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DownloadStateNoOp() {
	var x [1]struct{}
	_ = x[DownloadUnknown-(0)]
	_ = x[DownloadQueued-(1)]
	_ = x[DownloadDownloading-(2)]
	_ = x[DownloadComplete-(3)]
	_ = x[DownloadError-(4)]
}

var _DownloadStateValues = []DownloadState{DownloadUnknown, DownloadQueued, DownloadDownloading, DownloadComplete, DownloadError}

var _DownloadStateNameToValueMap = map[string]DownloadState{
	_DownloadStateName[0:15]:       DownloadUnknown,
	_DownloadStateLowerName[0:15]:  DownloadUnknown,
	_DownloadStateName[15:29]:      DownloadQueued,
	_DownloadStateLowerName[15:29]: DownloadQueued,
	_DownloadStateName[29:48]:      DownloadDownloading,
	_DownloadStateLowerName[29:48]: DownloadDownloading,
	_DownloadStateName[48:64]:      DownloadComplete,
	_DownloadStateLowerName[48:64]: DownloadComplete,
	_DownloadStateName[64:77]:      DownloadError,
	_DownloadStateLowerName[64:77]: DownloadError,
}

var _DownloadStateNames = []string{
	_DownloadStateName[0:15],
	_DownloadStateName[15:29],
	_DownloadStateName[29:48],
	_DownloadStateName[48:64],
	_DownloadStateName[64:77],
}

// DownloadStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DownloadStateString(s string) (DownloadState, error) {
	if val, ok := _DownloadStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DownloadStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DownloadState values", s)
}

// DownloadStateValues returns all values of the enum
func DownloadStateValues() []DownloadState {
	return _DownloadStateValues
}

// DownloadStateStrings returns a slice of all String values of the enum
func DownloadStateStrings() []string {
	strs := make([]string, len(_DownloadStateNames))
	copy(strs, _DownloadStateNames)
	return strs
}

// IsADownloadState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DownloadState) IsADownloadState() bool {
	for _, v := range _DownloadStateValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i DownloadState) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *DownloadState) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of DownloadState: %[1]T(%[1]v)", value)
	}

	val, err := DownloadStateString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
