// Code generated by "enumer -sql -type=ClientType -output=enum_client_type.go"; DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _ClientTypeName = "ClientUnknownClientTransmission"

var _ClientTypeIndex = [...]uint8{0, 13, 31}

const _ClientTypeLowerName = "clientunknownclienttransmission"

func (i ClientType) String() string {
	if i < 0 || i >= ClientType(len(_ClientTypeIndex)-1) {
		return fmt.Sprintf("ClientType(%d)", i)
	}
	return _ClientTypeName[_ClientTypeIndex[i]:_ClientTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ClientTypeNoOp() {
	var x [1]struct{}
	_ = x[ClientUnknown-(0)]
	_ = x[ClientTransmission-(1)]
}

var _ClientTypeValues = []ClientType{ClientUnknown, ClientTransmission}

var _ClientTypeNameToValueMap = map[string]ClientType{
	_ClientTypeName[0:13]:       ClientUnknown,
	_ClientTypeLowerName[0:13]:  ClientUnknown,
	_ClientTypeName[13:31]:      ClientTransmission,
	_ClientTypeLowerName[13:31]: ClientTransmission,
}

var _ClientTypeNames = []string{
	_ClientTypeName[0:13],
	_ClientTypeName[13:31],
}

// ClientTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ClientTypeString(s string) (ClientType, error) {
	if val, ok := _ClientTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ClientTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ClientType values", s)
}

// ClientTypeValues returns all values of the enum
func ClientTypeValues() []ClientType {
	return _ClientTypeValues
}

// ClientTypeStrings returns a slice of all String values of the enum
func ClientTypeStrings() []string {
	strs := make([]string, len(_ClientTypeNames))
	copy(strs, _ClientTypeNames)
	return strs
}

// IsAClientType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ClientType) IsAClientType() bool {
	for _, v := range _ClientTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i ClientType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ClientType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ClientType: %[1]T(%[1]v)", value)
	}

	val, err := ClientTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
