// Code generated by "enumer -sql -type=Role -output=enum_user_role.go"; DO NOT EDIT.

package user

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _RoleName = "OmnissiahMagosTechPriest"

var _RoleIndex = [...]uint8{0, 9, 14, 24}

const _RoleLowerName = "omnissiahmagostechpriest"

func (i Role) String() string {
	if i < 0 || i >= Role(len(_RoleIndex)-1) {
		return fmt.Sprintf("Role(%d)", i)
	}
	return _RoleName[_RoleIndex[i]:_RoleIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _RoleNoOp() {
	var x [1]struct{}
	_ = x[Omnissiah-(0)]
	_ = x[Magos-(1)]
	_ = x[TechPriest-(2)]
}

var _RoleValues = []Role{Omnissiah, Magos, TechPriest}

var _RoleNameToValueMap = map[string]Role{
	_RoleName[0:9]:        Omnissiah,
	_RoleLowerName[0:9]:   Omnissiah,
	_RoleName[9:14]:       Magos,
	_RoleLowerName[9:14]:  Magos,
	_RoleName[14:24]:      TechPriest,
	_RoleLowerName[14:24]: TechPriest,
}

var _RoleNames = []string{
	_RoleName[0:9],
	_RoleName[9:14],
	_RoleName[14:24],
}

// RoleString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func RoleString(s string) (Role, error) {
	if val, ok := _RoleNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _RoleNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Role values", s)
}

// RoleValues returns all values of the enum
func RoleValues() []Role {
	return _RoleValues
}

// RoleStrings returns a slice of all String values of the enum
func RoleStrings() []string {
	strs := make([]string, len(_RoleNames))
	copy(strs, _RoleNames)
	return strs
}

// IsARole returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Role) IsARole() bool {
	for _, v := range _RoleValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i Role) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Role) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Role: %[1]T(%[1]v)", value)
	}

	val, err := RoleString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
