// Code generated by "enumer -type=DownloadState -output=enum_downloadstate.go"; DO NOT EDIT.

package clients

import (
	"fmt"
	"strings"
)

const _DownloadStateName = "QueuedDownloadingCompleteError"

var _DownloadStateIndex = [...]uint8{0, 6, 17, 25, 30}

const _DownloadStateLowerName = "queueddownloadingcompleteerror"

func (i DownloadState) String() string {
	if i < 0 || i >= DownloadState(len(_DownloadStateIndex)-1) {
		return fmt.Sprintf("DownloadState(%d)", i)
	}
	return _DownloadStateName[_DownloadStateIndex[i]:_DownloadStateIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _DownloadStateNoOp() {
	var x [1]struct{}
	_ = x[Queued-(0)]
	_ = x[Downloading-(1)]
	_ = x[Complete-(2)]
	_ = x[Error-(3)]
}

var _DownloadStateValues = []DownloadState{Queued, Downloading, Complete, Error}

var _DownloadStateNameToValueMap = map[string]DownloadState{
	_DownloadStateName[0:6]:        Queued,
	_DownloadStateLowerName[0:6]:   Queued,
	_DownloadStateName[6:17]:       Downloading,
	_DownloadStateLowerName[6:17]:  Downloading,
	_DownloadStateName[17:25]:      Complete,
	_DownloadStateLowerName[17:25]: Complete,
	_DownloadStateName[25:30]:      Error,
	_DownloadStateLowerName[25:30]: Error,
}

var _DownloadStateNames = []string{
	_DownloadStateName[0:6],
	_DownloadStateName[6:17],
	_DownloadStateName[17:25],
	_DownloadStateName[25:30],
}

// DownloadStateString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func DownloadStateString(s string) (DownloadState, error) {
	if val, ok := _DownloadStateNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _DownloadStateNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to DownloadState values", s)
}

// DownloadStateValues returns all values of the enum
func DownloadStateValues() []DownloadState {
	return _DownloadStateValues
}

// DownloadStateStrings returns a slice of all String values of the enum
func DownloadStateStrings() []string {
	strs := make([]string, len(_DownloadStateNames))
	copy(strs, _DownloadStateNames)
	return strs
}

// IsADownloadState returns "true" if the value is listed in the enum definition. "false" otherwise
func (i DownloadState) IsADownloadState() bool {
	for _, v := range _DownloadStateValues {
		if i == v {
			return true
		}
	}
	return false
}
