syntax = "proto3";

package config.v1;

option go_package = "github.com/ra341/glacier/generated/config/v1";

service ConfigService {
  rpc Get(GetRequest) returns (GetResponse) {}
  rpc Set(SetRequest) returns (SetResponse) {}
  rpc ListFiles(ListFilesRequest) returns (ListFilesResponse) {}
  rpc GetField(GetFieldRequest) returns (GetFieldResponse) {}
  rpc SetField(SetFieldRequest) returns (SetFieldResponse) {}
}

message SetFieldRequest {
  string Field = 1;
  string Value = 2;
}

message SetFieldResponse {}

message GetFieldRequest {
  string Field = 1;
}

message GetFieldResponse {
  string Value = 1;
  string Error = 2;
}

message ListFilesRequest {
  string base = 1;
}

message ListFilesResponse {
  repeated string files = 1;
}

message SetRequest {
  string configSchema = 1;
}

message SetResponse {}

message GetRequest {}

message GetResponse {
  string configSchema = 1;
}
