// Code generated by "enumer -sql -type=SessionType -output=enum_session_type.go"; DO NOT EDIT.

package auth

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _SessionTypeName = "WebFrost"

var _SessionTypeIndex = [...]uint8{0, 3, 8}

const _SessionTypeLowerName = "webfrost"

func (i SessionType) String() string {
	if i < 0 || i >= SessionType(len(_SessionTypeIndex)-1) {
		return fmt.Sprintf("SessionType(%d)", i)
	}
	return _SessionTypeName[_SessionTypeIndex[i]:_SessionTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _SessionTypeNoOp() {
	var x [1]struct{}
	_ = x[Web-(0)]
	_ = x[Frost-(1)]
}

var _SessionTypeValues = []SessionType{Web, Frost}

var _SessionTypeNameToValueMap = map[string]SessionType{
	_SessionTypeName[0:3]:      Web,
	_SessionTypeLowerName[0:3]: Web,
	_SessionTypeName[3:8]:      Frost,
	_SessionTypeLowerName[3:8]: Frost,
}

var _SessionTypeNames = []string{
	_SessionTypeName[0:3],
	_SessionTypeName[3:8],
}

// SessionTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func SessionTypeString(s string) (SessionType, error) {
	if val, ok := _SessionTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _SessionTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to SessionType values", s)
}

// SessionTypeValues returns all values of the enum
func SessionTypeValues() []SessionType {
	return _SessionTypeValues
}

// SessionTypeStrings returns a slice of all String values of the enum
func SessionTypeStrings() []string {
	strs := make([]string, len(_SessionTypeNames))
	copy(strs, _SessionTypeNames)
	return strs
}

// IsASessionType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i SessionType) IsASessionType() bool {
	for _, v := range _SessionTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i SessionType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *SessionType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of SessionType: %[1]T(%[1]v)", value)
	}

	val, err := SessionTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
