syntax = "proto3";

package frost_library.v1;

option go_package = "github.com/ra341/glacier/generated/frost_library/v1";

import "library/v1/library.proto";

service FrostLibraryService {
  rpc ListFiles(ListFilesRequest) returns (ListFilesResponse) {}
  rpc ListDownloading(ListDownloadingRequest) returns (ListDownloadingResponse) {}
  rpc Get(GetRequest) returns (GetResponse) {}
  rpc Edit(EditRequest) returns (EditResponse) {}

  rpc LaunchFilePicker(LaunchFilePickerRequest) returns (LaunchFilePickerResponse) {}

  rpc Delete(DeleteRequest) returns (DeleteResponse) {}
  rpc GetByGameId(GetByGameIdRequest) returns (GetByGameIdResponse) {}
  rpc Launch(LaunchRequest) returns (LaunchResponse) {}

  rpc ThrottleSpeed(ThrottleSpeedRequest) returns (ThrottleSpeedResponse) {}
  rpc Download(DownloadRequest) returns (DownloadResponse) {}
  rpc Cancel(CancelRequest) returns (CancelResponse) {}
  rpc Pause(PauseRequest) returns (PauseResponse) {}
}

message ThrottleSpeedRequest {
  float limit = 1;
}

message ThrottleSpeedResponse {}


message LaunchFilePickerRequest {
  string baseDir = 1;
}

message LaunchFilePickerResponse {
  string path = 1;
}


message EditRequest {
  LocalGame LocalGame = 1;
}

message EditResponse {}


message LaunchRequest {
  uint64 Id = 1;
}

message LaunchResponse {}


message GetByGameIdRequest {
  uint64 id = 1;
  bool localDownload = 2;
}

message GetByGameIdResponse {
  LocalGame download = 1;
}


message PauseRequest {
  uint64 id = 1;
}

message PauseResponse {}

message CancelRequest {
  uint64 id = 1;
}

message CancelResponse {}


message ListFilesRequest {
  uint64 id = 1;
  string path = 2;
}

message ListFilesResponse {}

message GetRequest {
  uint64 id = 1;
}

message LocalDownload {
  string DownloadPath = 1;
  string Status = 2;
  string StatusMessage = 3;
  string Started = 4;
  string Done = 5;
}

message GamePlay {
  string LaunchExe = 2;
}

message LocalGame {
  uint64 ID = 1;

  uint64 GameID = 2;
  library.v1.Game game = 3;

  LocalDownload Download = 4;
  GamePlay Play = 5;
}

message GetResponse {
  LocalGame lg = 1;
}

message DeleteRequest {
  uint64 id = 1;
}

message DeleteResponse {}

message DownloadRequest {
  int64 gameId = 1;
  string downloadFolder = 2;
  // delete and redownload
  bool force = 3;
  // recheck against metadata download necessary files
  bool recheck = 4;
}

message DownloadResponse {}


message ListDownloadingRequest {}

message FileProgress {
  string Name = 1;
  uint64 Complete = 2;
  uint64 Left = 3;
}

message FolderProgress {
  int64 Complete = 1;
  int64 Left = 2;
  repeated FileProgress files = 3;
}

message DownloadProgress {
  uint64 ID = 5;
  string Thumbnail = 1;
  string Title = 2;
  LocalDownload download = 3;
  FolderProgress progress = 4;
}

message ListDownloadingResponse {
  repeated DownloadProgress downloads = 1;
}
