// Code generated by "enumer -type=AssetType -output=enum_asset_type.go"; DO NOT EDIT.

package assets

import (
	"fmt"
	"strings"
)

const _AssetTypeName = "AssetUnknownAssetThumbnailAssetBannerAssetTrailerAssetGameplayImageAssetGameplayVideoAssetArtwork"

var _AssetTypeIndex = [...]uint8{0, 12, 26, 37, 49, 67, 85, 97}

const _AssetTypeLowerName = "assetunknownassetthumbnailassetbannerassettrailerassetgameplayimageassetgameplayvideoassetartwork"

func (i AssetType) String() string {
	if i < 0 || i >= AssetType(len(_AssetTypeIndex)-1) {
		return fmt.Sprintf("AssetType(%d)", i)
	}
	return _AssetTypeName[_AssetTypeIndex[i]:_AssetTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _AssetTypeNoOp() {
	var x [1]struct{}
	_ = x[AssetUnknown-(0)]
	_ = x[AssetThumbnail-(1)]
	_ = x[AssetBanner-(2)]
	_ = x[AssetTrailer-(3)]
	_ = x[AssetGameplayImage-(4)]
	_ = x[AssetGameplayVideo-(5)]
	_ = x[AssetArtwork-(6)]
}

var _AssetTypeValues = []AssetType{AssetUnknown, AssetThumbnail, AssetBanner, AssetTrailer, AssetGameplayImage, AssetGameplayVideo, AssetArtwork}

var _AssetTypeNameToValueMap = map[string]AssetType{
	_AssetTypeName[0:12]:       AssetUnknown,
	_AssetTypeLowerName[0:12]:  AssetUnknown,
	_AssetTypeName[12:26]:      AssetThumbnail,
	_AssetTypeLowerName[12:26]: AssetThumbnail,
	_AssetTypeName[26:37]:      AssetBanner,
	_AssetTypeLowerName[26:37]: AssetBanner,
	_AssetTypeName[37:49]:      AssetTrailer,
	_AssetTypeLowerName[37:49]: AssetTrailer,
	_AssetTypeName[49:67]:      AssetGameplayImage,
	_AssetTypeLowerName[49:67]: AssetGameplayImage,
	_AssetTypeName[67:85]:      AssetGameplayVideo,
	_AssetTypeLowerName[67:85]: AssetGameplayVideo,
	_AssetTypeName[85:97]:      AssetArtwork,
	_AssetTypeLowerName[85:97]: AssetArtwork,
}

var _AssetTypeNames = []string{
	_AssetTypeName[0:12],
	_AssetTypeName[12:26],
	_AssetTypeName[26:37],
	_AssetTypeName[37:49],
	_AssetTypeName[49:67],
	_AssetTypeName[67:85],
	_AssetTypeName[85:97],
}

// AssetTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func AssetTypeString(s string) (AssetType, error) {
	if val, ok := _AssetTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _AssetTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to AssetType values", s)
}

// AssetTypeValues returns all values of the enum
func AssetTypeValues() []AssetType {
	return _AssetTypeValues
}

// AssetTypeStrings returns a slice of all String values of the enum
func AssetTypeStrings() []string {
	strs := make([]string, len(_AssetTypeNames))
	copy(strs, _AssetTypeNames)
	return strs
}

// IsAAssetType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i AssetType) IsAAssetType() bool {
	for _, v := range _AssetTypeValues {
		if i == v {
			return true
		}
	}
	return false
}
