// Code generated by "enumer -sql -type=GameType -output=enum_game_type.go"; DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _GameTypeName = "GameTypeUnknownGameTypeInstallerGameTypeStandalone"

var _GameTypeIndex = [...]uint8{0, 15, 32, 50}

const _GameTypeLowerName = "gametypeunknowngametypeinstallergametypestandalone"

func (i GameType) String() string {
	if i < 0 || i >= GameType(len(_GameTypeIndex)-1) {
		return fmt.Sprintf("GameType(%d)", i)
	}
	return _GameTypeName[_GameTypeIndex[i]:_GameTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _GameTypeNoOp() {
	var x [1]struct{}
	_ = x[GameTypeUnknown-(0)]
	_ = x[GameTypeInstaller-(1)]
	_ = x[GameTypeStandalone-(2)]
}

var _GameTypeValues = []GameType{GameTypeUnknown, GameTypeInstaller, GameTypeStandalone}

var _GameTypeNameToValueMap = map[string]GameType{
	_GameTypeName[0:15]:       GameTypeUnknown,
	_GameTypeLowerName[0:15]:  GameTypeUnknown,
	_GameTypeName[15:32]:      GameTypeInstaller,
	_GameTypeLowerName[15:32]: GameTypeInstaller,
	_GameTypeName[32:50]:      GameTypeStandalone,
	_GameTypeLowerName[32:50]: GameTypeStandalone,
}

var _GameTypeNames = []string{
	_GameTypeName[0:15],
	_GameTypeName[15:32],
	_GameTypeName[32:50],
}

// GameTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func GameTypeString(s string) (GameType, error) {
	if val, ok := _GameTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _GameTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to GameType values", s)
}

// GameTypeValues returns all values of the enum
func GameTypeValues() []GameType {
	return _GameTypeValues
}

// GameTypeStrings returns a slice of all String values of the enum
func GameTypeStrings() []string {
	strs := make([]string, len(_GameTypeNames))
	copy(strs, _GameTypeNames)
	return strs
}

// IsAGameType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i GameType) IsAGameType() bool {
	for _, v := range _GameTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i GameType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *GameType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of GameType: %[1]T(%[1]v)", value)
	}

	val, err := GameTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
