// Code generated by "enumer -sql -type=IndexerType -output=enum_indexer_type.go"; DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _IndexerTypeName = "IndexerUnknownIndexerHydra"

var _IndexerTypeIndex = [...]uint8{0, 14, 26}

const _IndexerTypeLowerName = "indexerunknownindexerhydra"

func (i IndexerType) String() string {
	if i < 0 || i >= IndexerType(len(_IndexerTypeIndex)-1) {
		return fmt.Sprintf("IndexerType(%d)", i)
	}
	return _IndexerTypeName[_IndexerTypeIndex[i]:_IndexerTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _IndexerTypeNoOp() {
	var x [1]struct{}
	_ = x[IndexerUnknown-(0)]
	_ = x[IndexerHydra-(1)]
}

var _IndexerTypeValues = []IndexerType{IndexerUnknown, IndexerHydra}

var _IndexerTypeNameToValueMap = map[string]IndexerType{
	_IndexerTypeName[0:14]:       IndexerUnknown,
	_IndexerTypeLowerName[0:14]:  IndexerUnknown,
	_IndexerTypeName[14:26]:      IndexerHydra,
	_IndexerTypeLowerName[14:26]: IndexerHydra,
}

var _IndexerTypeNames = []string{
	_IndexerTypeName[0:14],
	_IndexerTypeName[14:26],
}

// IndexerTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func IndexerTypeString(s string) (IndexerType, error) {
	if val, ok := _IndexerTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _IndexerTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to IndexerType values", s)
}

// IndexerTypeValues returns all values of the enum
func IndexerTypeValues() []IndexerType {
	return _IndexerTypeValues
}

// IndexerTypeStrings returns a slice of all String values of the enum
func IndexerTypeStrings() []string {
	strs := make([]string, len(_IndexerTypeNames))
	copy(strs, _IndexerTypeNames)
	return strs
}

// IsAIndexerType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i IndexerType) IsAIndexerType() bool {
	for _, v := range _IndexerTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i IndexerType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *IndexerType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of IndexerType: %[1]T(%[1]v)", value)
	}

	val, err := IndexerTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
