// Code generated by "enumer -sql -type=ServiceType -output=service_type.go"; DO NOT EDIT.

package services_manager

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _ServiceTypeName = "IndexerMetadataDownloader"

var _ServiceTypeIndex = [...]uint8{0, 7, 15, 25}

const _ServiceTypeLowerName = "indexermetadatadownloader"

func (i ServiceType) String() string {
	if i < 0 || i >= ServiceType(len(_ServiceTypeIndex)-1) {
		return fmt.Sprintf("ServiceType(%d)", i)
	}
	return _ServiceTypeName[_ServiceTypeIndex[i]:_ServiceTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ServiceTypeNoOp() {
	var x [1]struct{}
	_ = x[Indexer-(0)]
	_ = x[Metadata-(1)]
	_ = x[Downloader-(2)]
}

var _ServiceTypeValues = []ServiceType{Indexer, Metadata, Downloader}

var _ServiceTypeNameToValueMap = map[string]ServiceType{
	_ServiceTypeName[0:7]:        Indexer,
	_ServiceTypeLowerName[0:7]:   Indexer,
	_ServiceTypeName[7:15]:       Metadata,
	_ServiceTypeLowerName[7:15]:  Metadata,
	_ServiceTypeName[15:25]:      Downloader,
	_ServiceTypeLowerName[15:25]: Downloader,
}

var _ServiceTypeNames = []string{
	_ServiceTypeName[0:7],
	_ServiceTypeName[7:15],
	_ServiceTypeName[15:25],
}

// ServiceTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ServiceTypeString(s string) (ServiceType, error) {
	if val, ok := _ServiceTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ServiceTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ServiceType values", s)
}

// ServiceTypeValues returns all values of the enum
func ServiceTypeValues() []ServiceType {
	return _ServiceTypeValues
}

// ServiceTypeStrings returns a slice of all String values of the enum
func ServiceTypeStrings() []string {
	strs := make([]string, len(_ServiceTypeNames))
	copy(strs, _ServiceTypeNames)
	return strs
}

// IsAServiceType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ServiceType) IsAServiceType() bool {
	for _, v := range _ServiceTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i ServiceType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ServiceType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ServiceType: %[1]T(%[1]v)", value)
	}

	val, err := ServiceTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
