// Code generated by "enumer -sql -type=Status -output=enum_local_download_state.go"; DO NOT EDIT.

package download

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _StatusName = "StatusQueuedStatusMetadataStatusDownloadingStatusErrorStatusComplete"

var _StatusIndex = [...]uint8{0, 12, 26, 43, 54, 68}

const _StatusLowerName = "statusqueuedstatusmetadatastatusdownloadingstatuserrorstatuscomplete"

func (i Status) String() string {
	if i < 0 || i >= Status(len(_StatusIndex)-1) {
		return fmt.Sprintf("Status(%d)", i)
	}
	return _StatusName[_StatusIndex[i]:_StatusIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _StatusNoOp() {
	var x [1]struct{}
	_ = x[StatusQueued-(0)]
	_ = x[StatusMetadata-(1)]
	_ = x[StatusDownloading-(2)]
	_ = x[StatusError-(3)]
	_ = x[StatusComplete-(4)]
}

var _StatusValues = []Status{StatusQueued, StatusMetadata, StatusDownloading, StatusError, StatusComplete}

var _StatusNameToValueMap = map[string]Status{
	_StatusName[0:12]:       StatusQueued,
	_StatusLowerName[0:12]:  StatusQueued,
	_StatusName[12:26]:      StatusMetadata,
	_StatusLowerName[12:26]: StatusMetadata,
	_StatusName[26:43]:      StatusDownloading,
	_StatusLowerName[26:43]: StatusDownloading,
	_StatusName[43:54]:      StatusError,
	_StatusLowerName[43:54]: StatusError,
	_StatusName[54:68]:      StatusComplete,
	_StatusLowerName[54:68]: StatusComplete,
}

var _StatusNames = []string{
	_StatusName[0:12],
	_StatusName[12:26],
	_StatusName[26:43],
	_StatusName[43:54],
	_StatusName[54:68],
}

// StatusString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func StatusString(s string) (Status, error) {
	if val, ok := _StatusNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _StatusNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Status values", s)
}

// StatusValues returns all values of the enum
func StatusValues() []Status {
	return _StatusValues
}

// StatusStrings returns a slice of all String values of the enum
func StatusStrings() []string {
	strs := make([]string, len(_StatusNames))
	copy(strs, _StatusNames)
	return strs
}

// IsAStatus returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Status) IsAStatus() bool {
	for _, v := range _StatusValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i Status) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Status) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of Status: %[1]T(%[1]v)", value)
	}

	val, err := StatusString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
