// Code generated by "enumer -sql -type=ProviderType -output=enum_provider_type.go"; DO NOT EDIT.

package types

import (
	"database/sql/driver"
	"fmt"
	"strings"
)

const _ProviderTypeName = "ProviderUnknownProviderIGDB"

var _ProviderTypeIndex = [...]uint8{0, 15, 27}

const _ProviderTypeLowerName = "providerunknownproviderigdb"

func (i ProviderType) String() string {
	if i < 0 || i >= ProviderType(len(_ProviderTypeIndex)-1) {
		return fmt.Sprintf("ProviderType(%d)", i)
	}
	return _ProviderTypeName[_ProviderTypeIndex[i]:_ProviderTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ProviderTypeNoOp() {
	var x [1]struct{}
	_ = x[ProviderUnknown-(0)]
	_ = x[ProviderIGDB-(1)]
}

var _ProviderTypeValues = []ProviderType{ProviderUnknown, ProviderIGDB}

var _ProviderTypeNameToValueMap = map[string]ProviderType{
	_ProviderTypeName[0:15]:       ProviderUnknown,
	_ProviderTypeLowerName[0:15]:  ProviderUnknown,
	_ProviderTypeName[15:27]:      ProviderIGDB,
	_ProviderTypeLowerName[15:27]: ProviderIGDB,
}

var _ProviderTypeNames = []string{
	_ProviderTypeName[0:15],
	_ProviderTypeName[15:27],
}

// ProviderTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ProviderTypeString(s string) (ProviderType, error) {
	if val, ok := _ProviderTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ProviderTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ProviderType values", s)
}

// ProviderTypeValues returns all values of the enum
func ProviderTypeValues() []ProviderType {
	return _ProviderTypeValues
}

// ProviderTypeStrings returns a slice of all String values of the enum
func ProviderTypeStrings() []string {
	strs := make([]string, len(_ProviderTypeNames))
	copy(strs, _ProviderTypeNames)
	return strs
}

// IsAProviderType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ProviderType) IsAProviderType() bool {
	for _, v := range _ProviderTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

func (i ProviderType) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *ProviderType) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	var str string
	switch v := value.(type) {
	case []byte:
		str = string(v)
	case string:
		str = v
	case fmt.Stringer:
		str = v.String()
	default:
		return fmt.Errorf("invalid value of ProviderType: %[1]T(%[1]v)", value)
	}

	val, err := ProviderTypeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}
